/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jaxkjgtoonosmunqccto"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpheGtqZ3Rvb25vc211bnFjY3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDA1MzMsImV4cCI6MjA3MjYxNjUzM30.9x-XgItPHSNX5_DOpXInzm-ScnOEN9aJUN1Dsr77huc"